Repository prgrms-web-devcourse-final-project/WEB2_3_9crops_BE, pull requests merged in 2025-03, with the labels that each got.

#137 Refactor/temporary-token(wr9 87)
  src/main/java/io/crops/warmletter/domain/auth/dto/TokenStorageResponse.java
  src/main/java/io/crops/warmletter/domain/auth/service/AuthService.java
  src/main/java/io/crops/warmletter/domain/member/docs/MemberControllerDocs.java
  src/main/java/io/crops/warmletter/global/jwt/service/TokenBlacklistService.java
  src/main/java/io/crops/warmletter/global/oauth/handler/OAuth2AuthenticationSuccessHandler.java
  src/test/java/io/crops/warmletter/domain/auth/controller/AuthControllerTest.java
  src/test/java/io/crops/warmletter/domain/auth/service/AuthServiceTest.java
Labels: 🔨 Refactor

#140 Feature/get letter by status(wr9-69)
  src/main/java/io/crops/warmletter/domain/letter/controller/LetterController.java
  src/main/java/io/crops/warmletter/domain/letter/dto/response/LetterDraftResponse.java
  src/main/java/io/crops/warmletter/domain/letter/dto/response/LetterResponse.java
  src/main/java/io/crops/warmletter/domain/letter/dto/response/MailboxResponse.java
  src/main/java/io/crops/warmletter/domain/letter/dto/response/RandomLetterResponse.java
  src/main/java/io/crops/warmletter/domain/letter/dto/response/TemporaryMatchingResponse.java
  src/main/java/io/crops/warmletter/domain/letter/entity/LetterMatching.java
  src/main/java/io/crops/warmletter/domain/letter/enums/Category.java
  src/main/java/io/crops/warmletter/domain/letter/exception/CategoryNotFoundException.java
  src/main/java/io/crops/warmletter/domain/letter/repository/LetterMatchingRepository.java
  src/main/java/io/crops/warmletter/domain/letter/repository/LetterRepository.java
  src/main/java/io/crops/warmletter/domain/letter/service/LetterService.java
  src/main/java/io/crops/warmletter/domain/letter/service/MailboxService.java
  src/main/java/io/crops/warmletter/domain/letter/service/RandomLetterService.java
  src/main/java/io/crops/warmletter/domain/share/controller/SharePostLikeController.java
  src/main/java/io/crops/warmletter/global/error/common/ErrorCode.java
  src/test/java/io/crops/warmletter/domain/letter/controller/LettersControllerTest.java
  src/test/java/io/crops/warmletter/domain/letter/controller/LettersControllerUnitTest.java
  src/test/java/io/crops/warmletter/domain/letter/controller/RandomLetterControllerTest.java
  src/test/java/io/crops/warmletter/domain/letter/entity/LetterMatchingTest.java
  src/test/java/io/crops/warmletter/domain/letter/service/LetterServiceTest.java
  src/test/java/io/crops/warmletter/domain/letter/service/MailboxServiceTest.java
  src/test/java/io/crops/warmletter/domain/letter/service/RandomLetterServiceTest.java
Labels: ✨ Feature, ✅ Test

#135 refactor RequestId값 수정
  src/main/java/io/crops/warmletter/domain/share/dto/request/ShareProposalRequest.java
  src/main/java/io/crops/warmletter/domain/share/service/ShareProposalService.java
  src/test/java/io/crops/warmletter/domain/share/controller/ShareProposalControllerTest.java
  src/test/java/io/crops/warmletter/domain/share/dto/request/ShareProposalRequestTest.java
  src/test/java/io/crops/warmletter/domain/share/service/ShareProposalServiceTest.java
Labels: ✨ Feature, ✅ Test

#139 Feature/schedule-ban-members(wr9-88)
  src/main/java/io/crops/warmletter/domain/member/repository/MemberRepository.java
  src/main/java/io/crops/warmletter/domain/member/service/MemberSuspensionService.java
  src/main/java/io/crops/warmletter/global/config/ScheduleConfig.java
  src/test/java/io/crops/warmletter/domain/member/service/MemberSuspensionServiceTest.java
Labels: ✨ Feature, ✅ Test

#148 fix: 프록시 설정으로 인한 롤백 (WR9-87)
  src/main/java/io/crops/warmletter/domain/auth/service/AuthService.java
  src/main/java/io/crops/warmletter/global/config/CorsConfig.java
  src/main/java/io/crops/warmletter/global/jwt/provider/JwtTokenProvider.java
  src/main/java/io/crops/warmletter/global/oauth/handler/OAuth2AuthenticationSuccessHandler.java
  src/test/java/io/crops/warmletter/domain/auth/service/AuthServiceTest.java
Labels: 🐞 BugFix

#150 fix: reissue permit all 설정 (WR9-87)
  src/main/java/io/crops/warmletter/global/config/SecurityConfig.java
Labels: 🐞 BugFix

#154 Refactor/letter evaluation(wr9-95)
  src/main/java/io/crops/warmletter/domain/letter/controller/RandomLetterController.java
  src/main/java/io/crops/warmletter/domain/letter/controller/docs/RandomLetterControllerDocs.java
  src/main/java/io/crops/warmletter/domain/letter/dto/response/LetterResponse.java
  src/main/java/io/crops/warmletter/domain/letter/dto/response/MatchingResponse.java
  src/main/java/io/crops/warmletter/domain/letter/dto/response/TemporaryMatchingResponse.java
  src/main/java/io/crops/warmletter/domain/letter/entity/Letter.java
  src/main/java/io/crops/warmletter/domain/letter/service/LetterService.java
  src/main/java/io/crops/warmletter/domain/letter/service/RandomLetterService.java
  src/test/java/io/crops/warmletter/domain/letter/controller/RandomLetterControllerTest.java
  src/test/java/io/crops/warmletter/domain/letter/service/RandomLetterServiceConcurrencyTest.java
  src/test/java/io/crops/warmletter/domain/letter/service/RandomLetterServiceTest.java
Labels: ✨ Feature, 🔨 Refactor

#155 feat: 읽지 않은 편지 수 조회 API 배송상태 추가 수정 (WR9-97)
  src/main/java/io/crops/warmletter/domain/letter/controller/docs/LetterControllerDocs.java
  src/main/java/io/crops/warmletter/domain/letter/repository/LetterRepository.java
  src/main/java/io/crops/warmletter/domain/letter/service/LetterService.java
  src/test/java/io/crops/warmletter/domain/letter/service/LetterServiceTest.java
Labels: 🔨 Refactor, ✅ Test

#156 Refactor/event post comment alarm 2(wr9 90)
  src/main/java/io/crops/warmletter/domain/eventpost/controller/EventPostController.java
  src/main/java/io/crops/warmletter/domain/eventpost/dto/response/EventPostDetailResponse.java
  src/main/java/io/crops/warmletter/domain/eventpost/entity/EventPost.java
  src/main/java/io/crops/warmletter/domain/eventpost/exception/UsedEventPostNotFoundException.java
  src/main/java/io/crops/warmletter/domain/eventpost/repository/EventCommentRepository.java
  src/main/java/io/crops/warmletter/domain/eventpost/repository/EventPostRepository.java
  src/main/java/io/crops/warmletter/domain/eventpost/service/EventCommentService.java
  src/main/java/io/crops/warmletter/domain/eventpost/service/EventPostService.java
  src/main/java/io/crops/warmletter/domain/letter/service/LetterService.java
  src/main/java/io/crops/warmletter/domain/timeline/controller/TimelineController.java
  src/main/java/io/crops/warmletter/domain/timeline/dto/response/NotificationResponse.java
  src/main/java/io/crops/warmletter/domain/timeline/repository/TimelineRepository.java
  src/main/java/io/crops/warmletter/domain/timeline/service/NotificationService.java
  src/main/java/io/crops/warmletter/domain/timeline/service/TimelineService.java
  src/test/java/io/crops/warmletter/domain/eventpost/controller/EventPostControllerTest.java
  src/test/java/io/crops/warmletter/domain/eventpost/service/EventCommentServiceTest.java
  src/test/java/io/crops/warmletter/domain/eventpost/service/EventPostServiceTest.java
  src/test/java/io/crops/warmletter/domain/letter/service/LetterServiceTest.java
  src/test/java/io/crops/warmletter/domain/timeline/controller/TimelineControllerTest.java
  src/test/java/io/crops/warmletter/domain/timeline/service/NotificationServiceTest.java
  src/test/java/io/crops/warmletter/domain/timeline/service/TimelineServiceTest.java
Labels: 🔨 Refactor, ✅ Test

#159 Feature/delete draft letter(wr9 98)
  src/main/java/io/crops/warmletter/domain/letter/controller/LetterController.java
  src/main/java/io/crops/warmletter/domain/letter/repository/LetterRepository.java
  src/main/java/io/crops/warmletter/domain/letter/service/LetterService.java
  src/test/java/io/crops/warmletter/domain/letter/controller/LettersControllerUnitTest.java
  src/test/java/io/crops/warmletter/domain/letter/service/LetterServiceTest.java
Labels: ✨ Feature, ✅ Test

#162 feat: 편지 평가하기 이미 평가된 편지 예외처리 추가 (WR9-100)
  src/main/java/io/crops/warmletter/domain/letter/exception/AlreadyEvaluatedLetterException.java
  src/main/java/io/crops/warmletter/domain/letter/service/LetterService.java
  src/main/java/io/crops/warmletter/global/error/common/ErrorCode.java
  src/test/java/io/crops/warmletter/domain/letter/controller/LettersControllerUnitTest.java
  src/test/java/io/crops/warmletter/domain/letter/service/LetterServiceTest.java
Labels: 🔨 Refactor, ✅ Test

#166 Refactor/reissue-token(wr9 102)
  src/main/java/io/crops/warmletter/domain/auth/controller/AuthController.java
  src/main/java/io/crops/warmletter/domain/auth/docs/AuthControllerDocs.java
  src/main/java/io/crops/warmletter/domain/auth/service/AuthService.java
  src/test/java/io/crops/warmletter/domain/auth/controller/AuthControllerTest.java
  src/test/java/io/crops/warmletter/domain/auth/service/AuthServiceTest.java
Labels: 🔨 Refactor, ✅ Test

#171 fix: 알림 구독, 전송 부분 트랜잭션 어노테이션 삭제 (WR9-105) #170
  src/main/java/io/crops/warmletter/domain/timeline/service/NotificationService.java
Labels: 🐞 BugFix

#177 Feature/share posts me(wr9 109)
  src/main/java/io/crops/warmletter/domain/share/controller/SharePostController.java
  src/main/java/io/crops/warmletter/domain/share/repository/CustomSharePostRepository.java
  src/main/java/io/crops/warmletter/domain/share/repository/CustomSharePostRepositoryImpl.java
  src/main/java/io/crops/warmletter/domain/share/service/SharePostService.java
  src/test/java/io/crops/warmletter/domain/share/controller/SharePostControllerTest.java
  src/test/java/io/crops/warmletter/domain/share/service/SharePostServiceTest.java
Labels: ✨ Feature

#179 Refactor/improve alarm(wr9 106)
  src/main/java/io/crops/warmletter/domain/timeline/controller/NotificationController.java
  src/main/java/io/crops/warmletter/domain/timeline/controller/TimelineController.java
  src/main/java/io/crops/warmletter/domain/timeline/service/NotificationService.java
  src/main/java/io/crops/warmletter/domain/timeline/service/TimelineService.java
  src/test/java/io/crops/warmletter/domain/timeline/controller/NotificationControllerTest.java
  src/test/java/io/crops/warmletter/domain/timeline/controller/TimelineControllerTest.java
  src/test/java/io/crops/warmletter/domain/timeline/service/NotificationServiceTest.java
  src/test/java/io/crops/warmletter/domain/timeline/service/TimelineServiceTest.java
Labels: 🔨 Refactor, ✅ Test

#180 Feature/ai report(wr9 108)
  src/main/java/io/crops/warmletter/domain/report/service/ReportModerationService.java
  src/main/java/io/crops/warmletter/domain/report/service/ReportService.java
  src/main/resources/application.yml
  src/test/java/io/crops/warmletter/domain/report/service/ReportModerationServiceTest.java
  src/test/java/io/crops/warmletter/domain/report/service/ReportServiceTest.java
  src/test/resources/application-test.yml
Labels: ✨ Feature

#183 Refactor/single letter retrieval(wr9-107)
  src/main/java/io/crops/warmletter/domain/letter/dto/response/LetterResponse.java
  src/main/java/io/crops/warmletter/domain/letter/entity/LetterMatchingTimeout.java
  src/main/java/io/crops/warmletter/domain/letter/repository/LetterMatchingRepository.java
  src/main/java/io/crops/warmletter/domain/letter/repository/LetterRepository.java
  src/main/java/io/crops/warmletter/domain/letter/service/LetterService.java
  src/main/java/io/crops/warmletter/domain/letter/service/MailboxService.java
  src/test/java/io/crops/warmletter/domain/letter/service/MailboxServiceTest.java
Labels: 🔨 Refactor

#187 Setting/prod application yml(wr9 110)
  src/main/java/io/crops/warmletter/global/oauth/handler/OAuth2AuthenticationSuccessHandler.java
  src/main/resources/application.yml
Labels: 🐞 BugFix

#188 fix: domain 주소 설정 (WR9-110)
  src/main/java/io/crops/warmletter/domain/auth/service/AuthService.java
  src/main/java/io/crops/warmletter/global/oauth/handler/OAuth2AuthenticationSuccessHandler.java
Labels: 🐞 BugFix

#190 fix: 토큰 재발급은 JwtAuthenticationFilter 통과 시키기 추가 (WR9-114)
  src/main/java/io/crops/warmletter/global/jwt/filter/JwtAuthenticationFilter.java
Labels: 🐞 BugFix

#195 refactor: 답장만 임시저장 되도록 수정 (WR9-112)
  src/main/java/io/crops/warmletter/domain/letter/controller/LetterController.java
  src/main/java/io/crops/warmletter/domain/letter/dto/request/TemporarySaveLetterRequest.java
  src/main/java/io/crops/warmletter/domain/letter/entity/Letter.java
  src/main/java/io/crops/warmletter/domain/letter/service/LetterService.java
  src/main/resources/application.yml
  src/test/java/io/crops/warmletter/domain/letter/service/LetterServiceTest.java
Labels: 🔨 Refactor

#199 refactor: 내 편지함 목록 조회, 편지함 상세 조회 쿼리 수정 (WR9-119)
  src/main/java/io/crops/warmletter/domain/letter/repository/LetterMatchingRepository.java
  src/main/java/io/crops/warmletter/domain/letter/repository/LetterRepository.java
  src/main/java/io/crops/warmletter/domain/letter/service/MailboxService.java
  src/test/java/io/crops/warmletter/domain/letter/service/MailboxServiceTest.java
Labels: 🔨 Refactor

#200 Feature/share proposal detail(wr9 113)
  src/main/java/io/crops/warmletter/domain/share/controller/ShareProposalController.java
  src/main/java/io/crops/warmletter/domain/share/dto/response/ShareProposalDetailResponse.java
  src/main/java/io/crops/warmletter/domain/share/exception/ShareProposalAccessException.java
  src/main/java/io/crops/warmletter/domain/share/repository/CustomSharePostRepositoryImpl.java
  src/main/java/io/crops/warmletter/domain/share/repository/ShareProposalRepositoryCustom.java
  src/main/java/io/crops/warmletter/domain/share/repository/ShareProposalRepositoryImpl.java
  src/main/java/io/crops/warmletter/domain/share/service/ShareProposalService.java
  src/test/java/io/crops/warmletter/domain/share/controller/ShareProposalControllerTest.java
  src/test/java/io/crops/warmletter/domain/share/service/ShareProposalServiceTest.java
Labels: ✨ Feature

#204 refactor: 내 편지함에서 임시저장된 편지 안보이게 쿼리 수정 (WR9-121)
  src/main/java/io/crops/warmletter/domain/letter/repository/LetterMatchingRepository.java
  src/main/java/io/crops/warmletter/domain/letter/repository/LetterRepository.java
Labels: 🔨 Refactor

#205 fix: 회원탈퇴 시 리디렉션 url 설정 (WR9-120)
  src/main/java/io/crops/warmletter/global/config/SecurityConfig.java
  src/main/java/io/crops/warmletter/global/oauth/entity/OAuth2UserWithDeletedFlag.java
  src/main/java/io/crops/warmletter/global/oauth/handler/CustomOAuth2AuthenticationSuccessHandler.java
  src/main/java/io/crops/warmletter/global/oauth/service/CustomOAuth2UserService.java
Labels: 🔨 Refactor

#208 fix: 임시저장 편지 조회 API 500 에러 수정 (WR9-123)
  src/main/java/io/crops/warmletter/domain/letter/dto/response/LetterDraftResponse.java
  src/main/java/io/crops/warmletter/domain/letter/repository/LetterRepository.java
Labels: 🐞 BugFix, 🔨 Refactor

#210 refactor: 임시 저장된 편지 조회 시 매칭여부 제거 (WR9-124)
  src/main/java/io/crops/warmletter/domain/letter/dto/response/LetterDraftResponse.java
  src/main/java/io/crops/warmletter/domain/letter/dto/response/LetterResponse.java
  src/main/java/io/crops/warmletter/domain/letter/repository/LetterRepository.java
  src/test/java/io/crops/warmletter/domain/letter/service/LetterServiceTest.java
Labels: 🐞 BugFix

#212 Refactor/update temp letter response(wr9-125)
  src/main/java/io/crops/warmletter/domain/letter/dto/response/LetterDraftResponse.java
  src/main/java/io/crops/warmletter/domain/letter/dto/response/LetterResponse.java
  src/main/java/io/crops/warmletter/domain/letter/repository/LetterRepository.java
  src/main/java/io/crops/warmletter/domain/letter/service/LetterService.java
  src/main/java/io/crops/warmletter/global/schedule/DeliverySchedule.java
  src/test/java/io/crops/warmletter/domain/letter/service/LetterServiceTest.java
Labels: 🐞 BugFix, 🔨 Refactor

#219 refactor: 편지함 조회 응답 시 상대방 id값 추가 (WR9-128)
  src/main/java/io/crops/warmletter/domain/letter/dto/response/MailboxResponse.java
  src/main/java/io/crops/warmletter/domain/letter/repository/LetterMatchingRepository.java
Labels: 🔨 Refactor

#221 fix: JPQL 쿼리의 GROUP BY 누락 컬럼 오류 해결 -> only_full_group_by 모드 (WR9-130)
  src/main/java/io/crops/warmletter/domain/letter/repository/LetterMatchingRepository.java
Labels: 🐞 BugFix

#225 Feature/me add warning count(wr9 131)
  src/main/java/io/crops/warmletter/domain/member/dto/response/MeResponse.java
  src/main/java/io/crops/warmletter/domain/member/repository/MemberRepository.java
  src/test/java/io/crops/warmletter/domain/member/controller/MemberControllerTest.java
  src/test/java/io/crops/warmletter/domain/member/service/MemberServiceTest.java
Labels: ✨ Feature, ✅ Test

#226 Feature/get not read notification(wr9 132)
  src/main/java/io/crops/warmletter/domain/eventpost/service/EventCommentService.java
  src/main/java/io/crops/warmletter/domain/eventpost/service/EventPostService.java
  src/main/java/io/crops/warmletter/domain/timeline/controller/TimelineController.java
  src/main/java/io/crops/warmletter/domain/timeline/repository/TimelineRepository.java
  src/main/java/io/crops/warmletter/domain/timeline/service/NotificationService.java
  src/main/java/io/crops/warmletter/domain/timeline/service/TimelineService.java
  src/test/java/io/crops/warmletter/domain/eventpost/service/EventCommentServiceTest.java
  src/test/java/io/crops/warmletter/domain/eventpost/service/EventPostServiceTest.java
  src/test/java/io/crops/warmletter/domain/timeline/controller/TimelineControllerTest.java
  src/test/java/io/crops/warmletter/domain/timeline/service/TimelineServiceTest.java
Labels: ✨ Feature, ✅ Test

#235 refactor: 현재 작성 중인 특정 임시저장 편지만 찾아서 삭제 (WR9-137)
  src/main/java/io/crops/warmletter/domain/letter/dto/request/CreateLetterRequest.java
  src/main/java/io/crops/warmletter/domain/letter/repository/LetterRepository.java
  src/main/java/io/crops/warmletter/domain/letter/service/LetterService.java
  src/test/java/io/crops/warmletter/domain/letter/service/LetterServiceTest.java
Labels: 🔨 Refactor

#239 Refactor/alarm(wr9 139)
  src/main/java/io/crops/warmletter/domain/letter/service/LetterService.java
  src/main/java/io/crops/warmletter/domain/report/service/ReportService.java
  src/main/java/io/crops/warmletter/domain/share/repository/ShareProposalRepository.java
  src/main/java/io/crops/warmletter/domain/share/service/ShareProposalService.java
  src/main/java/io/crops/warmletter/domain/timeline/dto/request/NotificationRequest.java
  src/main/java/io/crops/warmletter/domain/timeline/facade/NotificationFacade.java
  src/main/java/io/crops/warmletter/domain/timeline/service/NotificationService.java
  src/main/java/io/crops/warmletter/global/schedule/DeliverySchedule.java
  src/test/java/io/crops/warmletter/domain/letter/service/LetterServiceTest.java
  src/test/java/io/crops/warmletter/domain/report/service/ReportServiceTest.java
  src/test/java/io/crops/warmletter/domain/share/service/ShareProposalServiceTest.java
  src/test/java/io/crops/warmletter/domain/timeline/facade/NotificationFacadeTest.java
  src/test/java/io/crops/warmletter/domain/timeline/service/NotificationServiceTest.java
Labels: 🐞 BugFix, 🔨 Refactor

#240 Feature/badword delete(wr9 138)
  src/main/java/io/crops/warmletter/domain/badword/controller/BadWordController.java
  src/main/java/io/crops/warmletter/domain/badword/service/BadWordService.java
  src/test/java/io/crops/warmletter/domain/badword/controller/BadWordControllerTest.java
  src/test/java/io/crops/warmletter/domain/badword/service/BadWordServiceTest.java
Labels: ✨ Feature

#243 fix: 오류 수정 테스트 (WR9-141) #242
  src/main/java/io/crops/warmletter/domain/timeline/service/NotificationService.java
Labels: 🐞 BugFix

#249 Fix/alarm report async(wr9 144)
  src/main/java/io/crops/warmletter/domain/report/service/ReportService.java
  src/test/java/io/crops/warmletter/domain/report/service/ReportServiceTest.java
Labels: 🐞 BugFix

#251 Refactor/delivery schedule individual transaction(wr9-142)
  src/main/java/io/crops/warmletter/domain/letter/entity/Letter.java
  src/main/java/io/crops/warmletter/domain/letter/service/LetterProcessingService.java
  src/main/java/io/crops/warmletter/global/config/AsyncConfig.java
  src/main/java/io/crops/warmletter/global/schedule/DeliverySchedule.java
  src/test/java/io/crops/warmletter/domain/letter/service/LetterProcessingServiceTest.java
Labels: 🔨 Refactor

#254 refactor 공유 제안 게시판 쿼리 수정
  src/main/java/io/crops/warmletter/domain/share/repository/CustomSharePostRepositoryImpl.java
Labels: 🔨 Refactor

#261 Setting/security-uri(wr9 150)
  src/main/java/io/crops/warmletter/domain/badword/controller/BadWordController.java
  src/main/java/io/crops/warmletter/domain/eventpost/controller/EventPostController.java
  src/main/java/io/crops/warmletter/domain/eventpost/entity/EventComment.java
  src/main/java/io/crops/warmletter/domain/report/controller/ReportController.java
  src/main/java/io/crops/warmletter/global/config/SecurityConfig.java
  src/main/java/io/crops/warmletter/global/jwt/provider/JwtTokenProvider.java
Labels: ⚙ Setting

#270 chore: 개발 프론트엔드 포트 추가 (WR9-155)
  src/main/java/io/crops/warmletter/global/config/CorsConfig.java
Labels: ⚙ Setting
